// <auto-generated />
using System;
using DbcLib;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace StockSharpDriver.Migrations.NLogs
{
    [DbContext(typeof(NLogsContext))]
    [Migration("20250429053609_NLogsContext001")]
    partial class NLogsContext001
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "6.0.36");

            modelBuilder.Entity("SharedLib.NLogRecordModelDB", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AllEventProperties")
                        .HasColumnType("TEXT");

                    b.Property<string>("ApplicationName")
                        .HasColumnType("TEXT");

                    b.Property<string>("CallSite")
                        .HasColumnType("TEXT");

                    b.Property<string>("ContextPrefix")
                        .HasColumnType("TEXT");

                    b.Property<string>("ExceptionMessage")
                        .HasColumnType("TEXT");

                    b.Property<string>("Logger")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordLevel")
                        .HasColumnType("TEXT");

                    b.Property<string>("RecordMessage")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RecordTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationName");

                    b.HasIndex("ContextPrefix");

                    b.HasIndex("Logger");

                    b.HasIndex("RecordLevel");

                    b.HasIndex("RecordTime");

                    b.ToTable("Logs");
                });
#pragma warning restore 612, 618
        }
    }
}
